spring:
  application:
    name: jt808
  datasource:
    #url: jdbc:mysql://192.168.8.88:3306/jt808?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    #username: iot
    #password: rongan@123
    url: jdbc:mysql://127.0.0.1:3702/jt808?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: iot808
    password: Ljt8e#80u
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 8
      transaction-isolation: TRANSACTION_READ_COMMITTED
      data-source-properties:
        useSSL: false
        sslMode: disabled
        serverTimezone: GMT+8
        characterEncoding: UTF-8
        zeroDateTimeBehavior: convertToNull
        allowPublicKeyRetrieval: true
        cachePrepStmts: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        prepStmtCacheSize: 64
        prepStmtCacheSqlLimit: 65535
        useServerPrepStmts: true
        useLocalTransactionState: true
        useLocalSessionState: true
        alwaysSendSetIsolation: false
        elideSetAutoCommits: true
        allowMultiQueries: true
        rewriteBatchedStatements: true
        enableQueryTimeouts: false
        maintainTimeStats: false
        useCompression: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

mybatis:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations:
    - classpath:/mapper/*.xml

server:
  port: 8000

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: centre-group
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    retry-next-server: false
    access-key: rkAdmin
    secret-key: J4ei3Wtq2

jt-server:
  jt808:
    enable: true
    port:
      udp: 7611
      tcp: 7611
    media-file:
      path: /data/jt_data/media_file
    alarm-file:
      host: 127.0.0.1
      port: 7612

  alarm-file:
    enable: true
    port: 7612
    path: /data/jt_data/alarm_file